<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/beds.php");
	include("$currDir/beds_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('beds');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "beds";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`beds`.`id`" => "id",
		"`beds`.`number`" => "number",
		"IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') /* Room */" => "room",
		"`beds`.`status`" => "status"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`beds`.`id`',
		2 => 2,
		3 => '`rooms1`.`name`',
		4 => 4
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`beds`.`id`" => "id",
		"`beds`.`number`" => "number",
		"IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') /* Room */" => "room",
		"`beds`.`status`" => "status"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`beds`.`id`" => "ID",
		"`beds`.`number`" => "Number",
		"IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') /* Room */" => "Room",
		"`beds`.`status`" => "Status"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`beds`.`id`" => "id",
		"`beds`.`number`" => "number",
		"IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') /* Room */" => "room",
		"`beds`.`status`" => "status"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'room' => 'Room');

	$x->QueryFrom = "`beds` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`beds`.`room` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "beds_view.php";
	$x->RedirectAfterInsert = "beds_view.php?SelectedID=#ID#";
	$x->TableTitle = "Beds";
	$x->TableIcon = "resources/table_icons/tag_green.png";
	$x->PrimaryKey = "`beds`.`id`";

	$x->ColWidth   = array(  150, 150, 150);
	$x->ColCaption = array("Number", "Room", "Status");
	$x->ColFieldName = array('number', 'room', 'status');
	$x->ColNumber  = array(2, 3, 4);

	// template paths below are based on the app main directory
	$x->Template = 'templates/beds_templateTV.html';
	$x->SelectedTemplate = 'templates/beds_templateTVS.html';
	$x->TemplateDV = 'templates/beds_templateDV.html';
	$x->TemplateDVP = 'templates/beds_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `beds`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='beds' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `beds`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='beds' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`beds`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: beds_init
	$render=TRUE;
	if(function_exists('beds_init')){
		$args=array();
		$render=beds_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: beds_header
	$headerCode='';
	if(function_exists('beds_header')){
		$args=array();
		$headerCode=beds_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: beds_footer
	$footerCode='';
	if(function_exists('beds_footer')){
		$args=array();
		$footerCode=beds_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>