<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/bill.php");
	include("$currDir/bill_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('bill');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "bill";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`bill`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "deceased",
		"IF(    CHAR_LENGTH(`invoices1`.`total`), CONCAT_WS('',   `invoices1`.`total`), '') /* Total */" => "total",
		"`bill`.`paid_amount`" => "paid_amount",
		"IF(    CHAR_LENGTH(`invoices1`.`balance`), CONCAT_WS('',   `invoices1`.`balance`), '') /* Balance */" => "balance"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`bill`.`id`',
		2 => 2,
		3 => '`invoices1`.`total`',
		4 => '`bill`.`paid_amount`',
		5 => '`invoices1`.`balance`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`bill`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "deceased",
		"IF(    CHAR_LENGTH(`invoices1`.`total`), CONCAT_WS('',   `invoices1`.`total`), '') /* Total */" => "total",
		"`bill`.`paid_amount`" => "paid_amount",
		"IF(    CHAR_LENGTH(`invoices1`.`balance`), CONCAT_WS('',   `invoices1`.`balance`), '') /* Balance */" => "balance"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`bill`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "Deceased",
		"IF(    CHAR_LENGTH(`invoices1`.`total`), CONCAT_WS('',   `invoices1`.`total`), '') /* Total */" => "Total",
		"`bill`.`paid_amount`" => "Paid amount",
		"IF(    CHAR_LENGTH(`invoices1`.`balance`), CONCAT_WS('',   `invoices1`.`balance`), '') /* Balance */" => "Balance"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`bill`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "deceased",
		"IF(    CHAR_LENGTH(`invoices1`.`total`), CONCAT_WS('',   `invoices1`.`total`), '') /* Total */" => "total",
		"`bill`.`paid_amount`" => "paid_amount",
		"IF(    CHAR_LENGTH(`invoices1`.`balance`), CONCAT_WS('',   `invoices1`.`balance`), '') /* Balance */" => "balance"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'deceased' => 'Deceased');

	$x->QueryFrom = "`bill` LEFT JOIN `invoices` as invoices1 ON `invoices1`.`id`=`bill`.`deceased` LEFT JOIN `incoming_deceased` as incoming_deceased1 ON `incoming_deceased1`.`id`=`invoices1`.`deceased` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "bill_view.php";
	$x->RedirectAfterInsert = "bill_view.php?SelectedID=#ID#";
	$x->TableTitle = "Bill";
	$x->TableIcon = "resources/table_icons/account_balances.png";
	$x->PrimaryKey = "`bill`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Deceased", "Total", "Paid amount", "Balance");
	$x->ColFieldName = array('deceased', 'total', 'paid_amount', 'balance');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/bill_templateTV.html';
	$x->SelectedTemplate = 'templates/bill_templateTVS.html';
	$x->TemplateDV = 'templates/bill_templateDV.html';
	$x->TemplateDVP = 'templates/bill_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `bill`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='bill' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `bill`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='bill' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`bill`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: bill_init
	$render=TRUE;
	if(function_exists('bill_init')){
		$args=array();
		$render=bill_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: bill_header
	$headerCode='';
	if(function_exists('bill_header')){
		$args=array();
		$headerCode=bill_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: bill_footer
	$footerCode='';
	if(function_exists('bill_footer')){
		$args=array();
		$footerCode=bill_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>