<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('bill');
	if(!$table_perms[0]){ die('// Access denied!'); }

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'deceased':
			if(!$id){
				?>
				$j('#total<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#balance<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `invoices`.`id` as 'id', IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') as 'deceased', IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms1`.`name`), '') as 'room', IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`) || CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`, '  Phone: ', `relatives_info1`.`phone_number`), '') as 'relative', `invoices`.`services` as 'services', `invoices`.`total` as 'total', `invoices`.`balance` as 'balance', if(`invoices`.`date`,date_format(`invoices`.`date`,'%m/%d/%Y'),'') as 'date' FROM `invoices` LEFT JOIN `incoming_deceased` as incoming_deceased1 ON `incoming_deceased1`.`id`=`invoices`.`deceased` LEFT JOIN `beds` as beds1 ON `beds1`.`id`=`incoming_deceased1`.`bed` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`beds1`.`room` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased1`.`relative_name`  WHERE `invoices`.`id`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#total<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['total']))); ?>&nbsp;');
			$j('#balance<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['balance']))); ?>&nbsp;');
			<?php
			break;


	}

?>