<?php

// Data functions (insert, update, delete, form) for table incoming_deceased

// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

function incoming_deceased_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('incoming_deceased');
	if(!$arrPerm[1]){
		return false;
	}

	$data['fullname'] = makeSafe($_REQUEST['fullname']);
		if($data['fullname'] == empty_lookup_value){ $data['fullname'] = ''; }
	$data['gender'] = makeSafe($_REQUEST['gender']);
		if($data['gender'] == empty_lookup_value){ $data['gender'] = ''; }
	$data['tag_number'] = makeSafe($_REQUEST['tag_number']);
		if($data['tag_number'] == empty_lookup_value){ $data['tag_number'] = ''; }
	$data['serial_number'] = makeSafe($_REQUEST['serial_number']);
		if($data['serial_number'] == empty_lookup_value){ $data['serial_number'] = ''; }
	$data['relative_name'] = makeSafe($_REQUEST['relative_name']);
		if($data['relative_name'] == empty_lookup_value){ $data['relative_name'] = ''; }
	$data['relative_number'] = makeSafe($_REQUEST['relative_name']);
		if($data['relative_number'] == empty_lookup_value){ $data['relative_number'] = ''; }
	$data['room'] = makeSafe($_REQUEST['room']);
		if($data['room'] == empty_lookup_value){ $data['room'] = ''; }
	$data['bed'] = makeSafe($_REQUEST['bed']);
		if($data['bed'] == empty_lookup_value){ $data['bed'] = ''; }
	$data['date'] = parseCode('<%%creationDate%%>', true, true);
	if($data['fullname']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Fullname': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['gender']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Gender': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['tag_number']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Tag number': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['serial_number']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Serial number': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['room']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Room': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['bed']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Bed': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: incoming_deceased_before_insert
	if(function_exists('incoming_deceased_before_insert')){
		$args=array();
		if(!incoming_deceased_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `incoming_deceased` set       `fullname`=' . (($data['fullname'] !== '' && $data['fullname'] !== NULL) ? "'{$data['fullname']}'" : 'NULL') . ', `gender`=' . (($data['gender'] !== '' && $data['gender'] !== NULL) ? "'{$data['gender']}'" : 'NULL') . ', `tag_number`=' . (($data['tag_number'] !== '' && $data['tag_number'] !== NULL) ? "'{$data['tag_number']}'" : 'NULL') . ', `serial_number`=' . (($data['serial_number'] !== '' && $data['serial_number'] !== NULL) ? "'{$data['serial_number']}'" : 'NULL') . ', `relative_name`=' . (($data['relative_name'] !== '' && $data['relative_name'] !== NULL) ? "'{$data['relative_name']}'" : 'NULL') . ', `relative_number`=' . (($data['relative_number'] !== '' && $data['relative_number'] !== NULL) ? "'{$data['relative_number']}'" : 'NULL') . ', `room`=' . (($data['room'] !== '' && $data['room'] !== NULL) ? "'{$data['room']}'" : 'NULL') . ', `bed`=' . (($data['bed'] !== '' && $data['bed'] !== NULL) ? "'{$data['bed']}'" : 'NULL') . ', `date`=' . "'{$data['date']}'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"incoming_deceased_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: incoming_deceased_after_insert
	if(function_exists('incoming_deceased_after_insert')){
		$res = sql("select * from `incoming_deceased` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!incoming_deceased_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('incoming_deceased', $recID, getLoggedMemberID());

	return $recID;
}

function incoming_deceased_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('incoming_deceased');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='incoming_deceased' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='incoming_deceased' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: incoming_deceased_before_delete
	if(function_exists('incoming_deceased_before_delete')){
		$args=array();
		if(!incoming_deceased_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: outgoing_deceased
	$res = sql("select `id` from `incoming_deceased` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `outgoing_deceased` where `fullname`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "outgoing_deceased", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "outgoing_deceased", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='incoming_deceased_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='incoming_deceased_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	// child table: invoices
	$res = sql("select `id` from `incoming_deceased` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `invoices` where `deceased`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "invoices", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "invoices", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='incoming_deceased_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='incoming_deceased_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `incoming_deceased` where `id`='$selected_id'", $eo);

	// hook: incoming_deceased_after_delete
	if(function_exists('incoming_deceased_after_delete')){
		$args=array();
		incoming_deceased_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='incoming_deceased' and pkValue='$selected_id'", $eo);
}

function incoming_deceased_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('incoming_deceased');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='incoming_deceased' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='incoming_deceased' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['fullname'] = makeSafe($_REQUEST['fullname']);
		if($data['fullname'] == empty_lookup_value){ $data['fullname'] = ''; }
	if($data['fullname']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fullname': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['gender'] = makeSafe($_REQUEST['gender']);
		if($data['gender'] == empty_lookup_value){ $data['gender'] = ''; }
	if($data['gender']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Gender': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['tag_number'] = makeSafe($_REQUEST['tag_number']);
		if($data['tag_number'] == empty_lookup_value){ $data['tag_number'] = ''; }
	if($data['tag_number']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Tag number': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['serial_number'] = makeSafe($_REQUEST['serial_number']);
		if($data['serial_number'] == empty_lookup_value){ $data['serial_number'] = ''; }
	if($data['serial_number']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Serial number': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['relative_name'] = makeSafe($_REQUEST['relative_name']);
		if($data['relative_name'] == empty_lookup_value){ $data['relative_name'] = ''; }
	$data['relative_number'] = makeSafe($_REQUEST['relative_name']);
		if($data['relative_number'] == empty_lookup_value){ $data['relative_number'] = ''; }
	$data['room'] = makeSafe($_REQUEST['room']);
		if($data['room'] == empty_lookup_value){ $data['room'] = ''; }
	if($data['room']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Room': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['bed'] = makeSafe($_REQUEST['bed']);
		if($data['bed'] == empty_lookup_value){ $data['bed'] = ''; }
	if($data['bed']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Bed': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['date'] = parseMySQLDate('', '<%%creationDate%%>');
	$data['selectedID']=makeSafe($selected_id);

	// hook: incoming_deceased_before_update
	if(function_exists('incoming_deceased_before_update')){
		$args=array();
		if(!incoming_deceased_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `incoming_deceased` set       `fullname`=' . (($data['fullname'] !== '' && $data['fullname'] !== NULL) ? "'{$data['fullname']}'" : 'NULL') . ', `gender`=' . (($data['gender'] !== '' && $data['gender'] !== NULL) ? "'{$data['gender']}'" : 'NULL') . ', `tag_number`=' . (($data['tag_number'] !== '' && $data['tag_number'] !== NULL) ? "'{$data['tag_number']}'" : 'NULL') . ', `serial_number`=' . (($data['serial_number'] !== '' && $data['serial_number'] !== NULL) ? "'{$data['serial_number']}'" : 'NULL') . ', `relative_name`=' . (($data['relative_name'] !== '' && $data['relative_name'] !== NULL) ? "'{$data['relative_name']}'" : 'NULL') . ', `relative_number`=' . (($data['relative_number'] !== '' && $data['relative_number'] !== NULL) ? "'{$data['relative_number']}'" : 'NULL') . ', `room`=' . (($data['room'] !== '' && $data['room'] !== NULL) ? "'{$data['room']}'" : 'NULL') . ', `bed`=' . (($data['bed'] !== '' && $data['bed'] !== NULL) ? "'{$data['bed']}'" : 'NULL') . ', `date`=`date`' . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="incoming_deceased_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: incoming_deceased_after_update
	if(function_exists('incoming_deceased_after_update')){
		$res = sql("SELECT * FROM `incoming_deceased` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!incoming_deceased_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='incoming_deceased' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function incoming_deceased_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('incoming_deceased');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_relative_name = thisOr(undo_magic_quotes($_REQUEST['filterer_relative_name']), '');
	$filterer_room = thisOr(undo_magic_quotes($_REQUEST['filterer_room']), '');
	$filterer_bed = thisOr(undo_magic_quotes($_REQUEST['filterer_bed']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: gender
	$combo_gender = new Combo;
	$combo_gender->ListType = 0;
	$combo_gender->MultipleSeparator = ', ';
	$combo_gender->ListBoxHeight = 10;
	$combo_gender->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/incoming_deceased.gender.csv')){
		$gender_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/incoming_deceased.gender.csv')));
		$combo_gender->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($gender_data)));
		$combo_gender->ListData = $combo_gender->ListItem;
	}else{
		$combo_gender->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("male;;female;;other")));
		$combo_gender->ListData = $combo_gender->ListItem;
	}
	$combo_gender->SelectName = 'gender';
	$combo_gender->AllowNull = false;
	// combobox: relative_name
	$combo_relative_name = new DataCombo;
	// combobox: room
	$combo_room = new DataCombo;
	// combobox: bed
	$combo_bed = new DataCombo;
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='incoming_deceased' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='incoming_deceased' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `incoming_deceased` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'incoming_deceased_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_gender->SelectedData = $row['gender'];
		$combo_relative_name->SelectedData = $row['relative_name'];
		$combo_room->SelectedData = $row['room'];
		$combo_bed->SelectedData = $row['bed'];
		$combo_date->DefaultDate = $row['date'];
	}else{
		$combo_gender->SelectedText = ( $_REQUEST['FilterField'][1]=='3' && $_REQUEST['FilterOperator'][1]=='<=>' ? (get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]) : "");
		$combo_relative_name->SelectedData = $filterer_relative_name;
		$combo_room->SelectedData = $filterer_room;
		$combo_bed->SelectedData = $filterer_bed;
	}
	$combo_gender->Render();
	$combo_relative_name->HTML = '<span id="relative_name-container' . $rnd1 . '"></span><input type="hidden" name="relative_name" id="relative_name' . $rnd1 . '" value="' . html_attr($combo_relative_name->SelectedData) . '">';
	$combo_relative_name->MatchText = '<span id="relative_name-container-readonly' . $rnd1 . '"></span><input type="hidden" name="relative_name" id="relative_name' . $rnd1 . '" value="' . html_attr($combo_relative_name->SelectedData) . '">';
	$combo_room->HTML = '<span id="room-container' . $rnd1 . '"></span><input type="hidden" name="room" id="room' . $rnd1 . '" value="' . html_attr($combo_room->SelectedData) . '">';
	$combo_room->MatchText = '<span id="room-container-readonly' . $rnd1 . '"></span><input type="hidden" name="room" id="room' . $rnd1 . '" value="' . html_attr($combo_room->SelectedData) . '">';
	$combo_bed->HTML = '<span id="bed-container' . $rnd1 . '"></span><input type="hidden" name="bed" id="bed' . $rnd1 . '" value="' . html_attr($combo_bed->SelectedData) . '">';
	$combo_bed->MatchText = '<span id="bed-container-readonly' . $rnd1 . '"></span><input type="hidden" name="bed" id="bed' . $rnd1 . '" value="' . html_attr($combo_bed->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_relative_name__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['relative_name'] : $filterer_relative_name); ?>"};
		AppGini.current_room__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['room'] : $filterer_room); ?>"};
		AppGini.current_bed__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['bed'] : $filterer_bed); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(relative_name_reload__RAND__) == 'function') relative_name_reload__RAND__();
				if(typeof(room_reload__RAND__) == 'function') room_reload__RAND__();
				if(typeof(bed_reload__RAND__) == 'function') bed_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function relative_name_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#relative_name-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_relative_name__RAND__.value, t: 'incoming_deceased', f: 'relative_name' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="relative_name"]').val(resp.results[0].id);
							$j('[id=relative_name-container-readonly__RAND__]').html('<span id="relative_name-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=relatives_info_view_parent]').hide(); }else{ $j('.btn[id=relatives_info_view_parent]').show(); }


							if(typeof(relative_name_update_autofills__RAND__) == 'function') relative_name_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'incoming_deceased', f: 'relative_name' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_relative_name__RAND__.value = e.added.id;
				AppGini.current_relative_name__RAND__.text = e.added.text;
				$j('[name="relative_name"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=relatives_info_view_parent]').hide(); }else{ $j('.btn[id=relatives_info_view_parent]').show(); }


				if(typeof(relative_name_update_autofills__RAND__) == 'function') relative_name_update_autofills__RAND__();
			});

			if(!$j("#relative_name-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_relative_name__RAND__.value, t: 'incoming_deceased', f: 'relative_name' },
					success: function(resp){
						$j('[name="relative_name"]').val(resp.results[0].id);
						$j('[id=relative_name-container-readonly__RAND__]').html('<span id="relative_name-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=relatives_info_view_parent]').hide(); }else{ $j('.btn[id=relatives_info_view_parent]').show(); }

						if(typeof(relative_name_update_autofills__RAND__) == 'function') relative_name_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_relative_name__RAND__.value, t: 'incoming_deceased', f: 'relative_name' },
				success: function(resp){
					$j('[id=relative_name-container__RAND__], [id=relative_name-container-readonly__RAND__]').html('<span id="relative_name-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=relatives_info_view_parent]').hide(); }else{ $j('.btn[id=relatives_info_view_parent]').show(); }

					if(typeof(relative_name_update_autofills__RAND__) == 'function') relative_name_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function room_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#room-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_room__RAND__.value, t: 'incoming_deceased', f: 'room' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="room"]').val(resp.results[0].id);
							$j('[id=room-container-readonly__RAND__]').html('<span id="room-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=rooms_view_parent]').hide(); }else{ $j('.btn[id=rooms_view_parent]').show(); }


							if(typeof(room_update_autofills__RAND__) == 'function') room_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'incoming_deceased', f: 'room' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_room__RAND__.value = e.added.id;
				AppGini.current_room__RAND__.text = e.added.text;
				$j('[name="room"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=rooms_view_parent]').hide(); }else{ $j('.btn[id=rooms_view_parent]').show(); }


				if(typeof(room_update_autofills__RAND__) == 'function') room_update_autofills__RAND__();
			});

			if(!$j("#room-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_room__RAND__.value, t: 'incoming_deceased', f: 'room' },
					success: function(resp){
						$j('[name="room"]').val(resp.results[0].id);
						$j('[id=room-container-readonly__RAND__]').html('<span id="room-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=rooms_view_parent]').hide(); }else{ $j('.btn[id=rooms_view_parent]').show(); }

						if(typeof(room_update_autofills__RAND__) == 'function') room_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_room__RAND__.value, t: 'incoming_deceased', f: 'room' },
				success: function(resp){
					$j('[id=room-container__RAND__], [id=room-container-readonly__RAND__]').html('<span id="room-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=rooms_view_parent]').hide(); }else{ $j('.btn[id=rooms_view_parent]').show(); }

					if(typeof(room_update_autofills__RAND__) == 'function') room_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function bed_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#bed-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_bed__RAND__.value, t: 'incoming_deceased', f: 'bed' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="bed"]').val(resp.results[0].id);
							$j('[id=bed-container-readonly__RAND__]').html('<span id="bed-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=beds_view_parent]').hide(); }else{ $j('.btn[id=beds_view_parent]').show(); }


							if(typeof(bed_update_autofills__RAND__) == 'function') bed_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'incoming_deceased', f: 'bed' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_bed__RAND__.value = e.added.id;
				AppGini.current_bed__RAND__.text = e.added.text;
				$j('[name="bed"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=beds_view_parent]').hide(); }else{ $j('.btn[id=beds_view_parent]').show(); }


				if(typeof(bed_update_autofills__RAND__) == 'function') bed_update_autofills__RAND__();
			});

			if(!$j("#bed-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_bed__RAND__.value, t: 'incoming_deceased', f: 'bed' },
					success: function(resp){
						$j('[name="bed"]').val(resp.results[0].id);
						$j('[id=bed-container-readonly__RAND__]').html('<span id="bed-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=beds_view_parent]').hide(); }else{ $j('.btn[id=beds_view_parent]').show(); }

						if(typeof(bed_update_autofills__RAND__) == 'function') bed_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_bed__RAND__.value, t: 'incoming_deceased', f: 'bed' },
				success: function(resp){
					$j('[id=bed-container__RAND__], [id=bed-container-readonly__RAND__]').html('<span id="bed-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=beds_view_parent]').hide(); }else{ $j('.btn[id=beds_view_parent]').show(); }

					if(typeof(bed_update_autofills__RAND__) == 'function') bed_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/incoming_deceased_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/incoming_deceased_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Incoming deceased details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return incoming_deceased_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return incoming_deceased_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return incoming_deceased_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#fullname').replaceWith('<div class=\"form-control-static\" id=\"fullname\">' + (jQuery('#fullname').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#gender').replaceWith('<div class=\"form-control-static\" id=\"gender\">' + (jQuery('#gender').val() || '') + '</div>'); jQuery('#gender-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#tag_number').replaceWith('<div class=\"form-control-static\" id=\"tag_number\">' + (jQuery('#tag_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#serial_number').replaceWith('<div class=\"form-control-static\" id=\"serial_number\">' + (jQuery('#serial_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#relative_name').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#relative_name_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#room').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#room_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#bed').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#bed_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(gender)%%>', $combo_gender->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(gender)%%>', $combo_gender->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(relative_name)%%>', $combo_relative_name->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(relative_name)%%>', $combo_relative_name->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(relative_name)%%>', urlencode($combo_relative_name->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(room)%%>', $combo_room->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(room)%%>', $combo_room->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(room)%%>', urlencode($combo_room->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(bed)%%>', $combo_bed->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(bed)%%>', $combo_bed->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(bed)%%>', urlencode($combo_bed->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : $combo_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'relative_name' => array('relatives_info', 'Relative name'), 'room' => array('rooms', 'Room'), 'bed' => array('beds', 'Bed'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fullname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(gender)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tag_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(serial_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(relative_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(room)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(bed)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fullname)%%>', safe_html($urow['fullname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fullname)%%>', html_attr($row['fullname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fullname)%%>', urlencode($urow['fullname']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(gender)%%>', safe_html($urow['gender']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(gender)%%>', html_attr($row['gender']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(gender)%%>', urlencode($urow['gender']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tag_number)%%>', safe_html($urow['tag_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tag_number)%%>', html_attr($row['tag_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tag_number)%%>', urlencode($urow['tag_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(serial_number)%%>', safe_html($urow['serial_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(serial_number)%%>', html_attr($row['serial_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serial_number)%%>', urlencode($urow['serial_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(relative_name)%%>', safe_html($urow['relative_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(relative_name)%%>', html_attr($row['relative_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(relative_name)%%>', urlencode($urow['relative_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(room)%%>', safe_html($urow['room']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(room)%%>', html_attr($row['room']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(room)%%>', urlencode($urow['room']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(bed)%%>', safe_html($urow['bed']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(bed)%%>', html_attr($row['bed']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(bed)%%>', urlencode($urow['bed']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', @date('m/d/Y', @strtotime(html_attr($row['date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['date'])))), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fullname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fullname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(gender)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(gender)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tag_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tag_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(serial_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(serial_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(relative_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(relative_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(room)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(room)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(bed)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(bed)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('<%%creationDate%%>'), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\trelative_name_update_autofills$rnd1 = function(){\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint){
		$templateCode .= "\t\t\turl: 'incoming_deceased_autofill.php?rnd1=$rnd1&mfk=relative_name&id=' + encodeURIComponent('".addslashes($row['relative_name'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "', type: 'GET'\n";
	}else{
		$templateCode .= "\t\t\turl: 'incoming_deceased_autofill.php?rnd1=$rnd1&mfk=relative_name&id=' + encodeURIComponent(AppGini.current_relative_name{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "', type: 'GET', beforeSend: function(){ /* */ \$j('#relative_name$rnd1').prop('disabled', true); \$j('#relative_nameLoading').html('<img src=loading.gif align=top>'); }, complete: function(){".(($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#relative_name$rnd1').prop('disabled', false); " : "\$j('#relative_name$rnd1').prop('disabled', true); ")."\$j('#relative_nameLoading').html('');}\n";
	}
	$templateCode.="\t\t});\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$j('#relative_name_caption').length) \$j('#relative_name_caption').click(function(){ /* */ relative_name_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('incoming_deceased');
	if($selected_id){
		$jdata = get_joined_record('incoming_deceased', $selected_id);
		if($jdata === false) $jdata = get_defaults('incoming_deceased');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('html_attr_tags_ok', $rdata)),
		'jdata' => array_map('nl2br', array_map('html_attr_tags_ok', $jdata))
	);
	$templateCode .= loadView('incoming_deceased-ajax-cache', $cache_data);

	// hook: incoming_deceased_dv
	if(function_exists('incoming_deceased_dv')){
		$args=array();
		incoming_deceased_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>