<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/invoices.php");
	include("$currDir/invoices_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('invoices');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "invoices";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`invoices`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "deceased",
		"IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms1`.`name`), '') /* Bed/Room */" => "room",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`) || CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`, '  Phone: ', `relatives_info1`.`phone_number`), '') /* Relative */" => "relative",
		"`invoices`.`services`" => "services",
		"`invoices`.`total`" => "total",
		"`invoices`.`balance`" => "balance",
		"if(`invoices`.`date`,date_format(`invoices`.`date`,'%m/%d/%Y'),'')" => "date"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`invoices`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`invoices`.`total`',
		7 => '`invoices`.`balance`',
		8 => '`invoices`.`date`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`invoices`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "deceased",
		"IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms1`.`name`), '') /* Bed/Room */" => "room",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`) || CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`, '  Phone: ', `relatives_info1`.`phone_number`), '') /* Relative */" => "relative",
		"`invoices`.`services`" => "services",
		"`invoices`.`total`" => "total",
		"`invoices`.`balance`" => "balance",
		"if(`invoices`.`date`,date_format(`invoices`.`date`,'%m/%d/%Y'),'')" => "date"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`invoices`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "Deceased",
		"IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms1`.`name`), '') /* Bed/Room */" => "Bed/Room",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`) || CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`, '  Phone: ', `relatives_info1`.`phone_number`), '') /* Relative */" => "Relative",
		"`invoices`.`services`" => "Services",
		"`invoices`.`total`" => "Total",
		"`invoices`.`balance`" => "Balance",
		"`invoices`.`date`" => "Date"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`invoices`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') /* Deceased */" => "deceased",
		"IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms1`.`name`), '') /* Bed/Room */" => "room",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`) || CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`, '  Phone: ', `relatives_info1`.`phone_number`), '') /* Relative */" => "relative",
		"`invoices`.`services`" => "services",
		"`invoices`.`total`" => "total",
		"`invoices`.`balance`" => "balance",
		"if(`invoices`.`date`,date_format(`invoices`.`date`,'%m/%d/%Y'),'')" => "date"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'deceased' => 'Deceased');

	$x->QueryFrom = "`invoices` LEFT JOIN `incoming_deceased` as incoming_deceased1 ON `incoming_deceased1`.`id`=`invoices`.`deceased` LEFT JOIN `beds` as beds1 ON `beds1`.`id`=`incoming_deceased1`.`bed` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`beds1`.`room` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased1`.`relative_name` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "invoices_view.php";
	$x->RedirectAfterInsert = "invoices_view.php?SelectedID=#ID#";
	$x->TableTitle = "Invoices";
	$x->TableIcon = "resources/table_icons/card_money.png";
	$x->PrimaryKey = "`invoices`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Deceased", "Bed/Room", "Relative", "Services", "Total", "Balance", "Date");
	$x->ColFieldName = array('deceased', 'room', 'relative', 'services', 'total', 'balance', 'date');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8);

	// template paths below are based on the app main directory
	$x->Template = 'templates/invoices_templateTV.html';
	$x->SelectedTemplate = 'templates/invoices_templateTVS.html';
	$x->TemplateDV = 'templates/invoices_templateDV.html';
	$x->TemplateDVP = 'templates/invoices_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `invoices`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='invoices' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `invoices`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='invoices' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`invoices`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: invoices_init
	$render=TRUE;
	if(function_exists('invoices_init')){
		$args=array();
		$render=invoices_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: invoices_header
	$headerCode='';
	if(function_exists('invoices_header')){
		$args=array();
		$headerCode=invoices_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: invoices_footer
	$footerCode='';
	if(function_exists('invoices_footer')){
		$args=array();
		$footerCode=invoices_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>