<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/outgoing_deceased.php");
	include("$currDir/outgoing_deceased_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('outgoing_deceased');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "outgoing_deceased";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`outgoing_deceased`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`), CONCAT_WS('',   `incoming_deceased1`.`fullname`), '') /* Fullname */" => "fullname",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`gender`), CONCAT_WS('',   `incoming_deceased1`.`gender`), '') /* Gender */" => "gender",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`tag_number`), '') /* Tag number */" => "tag_number",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`serial_number`), CONCAT_WS('',   `incoming_deceased1`.`serial_number`), '') /* Serial number */" => "serial_number",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') /* Relative name */" => "relative_name",
		"IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') /* Relative phone number */" => "relative_phone_number",
		"if(`outgoing_deceased`.`date`,date_format(`outgoing_deceased`.`date`,'%m/%d/%Y'),'')" => "date",
		"`outgoing_deceased`.`car_out_number`" => "car_out_number"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`outgoing_deceased`.`id`',
		2 => '`incoming_deceased1`.`fullname`',
		3 => '`incoming_deceased1`.`gender`',
		4 => '`incoming_deceased1`.`tag_number`',
		5 => '`incoming_deceased1`.`serial_number`',
		6 => 6,
		7 => 7,
		8 => '`outgoing_deceased`.`date`',
		9 => 9
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`outgoing_deceased`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`), CONCAT_WS('',   `incoming_deceased1`.`fullname`), '') /* Fullname */" => "fullname",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`gender`), CONCAT_WS('',   `incoming_deceased1`.`gender`), '') /* Gender */" => "gender",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`tag_number`), '') /* Tag number */" => "tag_number",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`serial_number`), CONCAT_WS('',   `incoming_deceased1`.`serial_number`), '') /* Serial number */" => "serial_number",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') /* Relative name */" => "relative_name",
		"IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') /* Relative phone number */" => "relative_phone_number",
		"if(`outgoing_deceased`.`date`,date_format(`outgoing_deceased`.`date`,'%m/%d/%Y'),'')" => "date",
		"`outgoing_deceased`.`car_out_number`" => "car_out_number"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`outgoing_deceased`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`), CONCAT_WS('',   `incoming_deceased1`.`fullname`), '') /* Fullname */" => "Fullname",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`gender`), CONCAT_WS('',   `incoming_deceased1`.`gender`), '') /* Gender */" => "Gender",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`tag_number`), '') /* Tag number */" => "Tag number",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`serial_number`), CONCAT_WS('',   `incoming_deceased1`.`serial_number`), '') /* Serial number */" => "Serial number",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') /* Relative name */" => "Relative name",
		"IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') /* Relative phone number */" => "Relative phone number",
		"`outgoing_deceased`.`date`" => "Date",
		"`outgoing_deceased`.`car_out_number`" => "Car out number"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`outgoing_deceased`.`id`" => "id",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`), CONCAT_WS('',   `incoming_deceased1`.`fullname`), '') /* Fullname */" => "fullname",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`gender`), CONCAT_WS('',   `incoming_deceased1`.`gender`), '') /* Gender */" => "gender",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`tag_number`), '') /* Tag number */" => "tag_number",
		"IF(    CHAR_LENGTH(`incoming_deceased1`.`serial_number`), CONCAT_WS('',   `incoming_deceased1`.`serial_number`), '') /* Serial number */" => "serial_number",
		"IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') /* Relative name */" => "relative_name",
		"IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') /* Relative phone number */" => "relative_phone_number",
		"if(`outgoing_deceased`.`date`,date_format(`outgoing_deceased`.`date`,'%m/%d/%Y'),'')" => "date",
		"`outgoing_deceased`.`car_out_number`" => "car_out_number"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'fullname' => 'Fullname');

	$x->QueryFrom = "`outgoing_deceased` LEFT JOIN `incoming_deceased` as incoming_deceased1 ON `incoming_deceased1`.`id`=`outgoing_deceased`.`fullname` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased1`.`relative_name` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "outgoing_deceased_view.php";
	$x->RedirectAfterInsert = "outgoing_deceased_view.php?SelectedID=#ID#";
	$x->TableTitle = "Outgoing deceased";
	$x->TableIcon = "resources/table_icons/application_side_contract.png";
	$x->PrimaryKey = "`outgoing_deceased`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Fullname", "Gender", "Tag number", "Serial number", "Relative name", "Relative phone number", "Date", "Car out number");
	$x->ColFieldName = array('fullname', 'gender', 'tag_number', 'serial_number', 'relative_name', 'relative_phone_number', 'date', 'car_out_number');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9);

	// template paths below are based on the app main directory
	$x->Template = 'templates/outgoing_deceased_templateTV.html';
	$x->SelectedTemplate = 'templates/outgoing_deceased_templateTVS.html';
	$x->TemplateDV = 'templates/outgoing_deceased_templateDV.html';
	$x->TemplateDVP = 'templates/outgoing_deceased_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `outgoing_deceased`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='outgoing_deceased' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `outgoing_deceased`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='outgoing_deceased' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`outgoing_deceased`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: outgoing_deceased_init
	$render=TRUE;
	if(function_exists('outgoing_deceased_init')){
		$args=array();
		$render=outgoing_deceased_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: outgoing_deceased_header
	$headerCode='';
	if(function_exists('outgoing_deceased_header')){
		$args=array();
		$headerCode=outgoing_deceased_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: outgoing_deceased_footer
	$footerCode='';
	if(function_exists('outgoing_deceased_footer')){
		$args=array();
		$footerCode=outgoing_deceased_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>