<?php

// Data functions (insert, update, delete, form) for table outgoing_deceased

// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

function outgoing_deceased_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('outgoing_deceased');
	if(!$arrPerm[1]){
		return false;
	}

	$data['fullname'] = makeSafe($_REQUEST['fullname']);
		if($data['fullname'] == empty_lookup_value){ $data['fullname'] = ''; }
	$data['gender'] = makeSafe($_REQUEST['fullname']);
		if($data['gender'] == empty_lookup_value){ $data['gender'] = ''; }
	$data['tag_number'] = makeSafe($_REQUEST['fullname']);
		if($data['tag_number'] == empty_lookup_value){ $data['tag_number'] = ''; }
	$data['serial_number'] = makeSafe($_REQUEST['fullname']);
		if($data['serial_number'] == empty_lookup_value){ $data['serial_number'] = ''; }
	$data['relative_name'] = makeSafe($_REQUEST['fullname']);
		if($data['relative_name'] == empty_lookup_value){ $data['relative_name'] = ''; }
	$data['relative_phone_number'] = makeSafe($_REQUEST['fullname']);
		if($data['relative_phone_number'] == empty_lookup_value){ $data['relative_phone_number'] = ''; }
	$data['date'] = parseCode('<%%creationDate%%>', true, true);
	$data['car_out_number'] = makeSafe($_REQUEST['car_out_number']);
		if($data['car_out_number'] == empty_lookup_value){ $data['car_out_number'] = ''; }
	if($data['fullname']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Fullname': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: outgoing_deceased_before_insert
	if(function_exists('outgoing_deceased_before_insert')){
		$args=array();
		if(!outgoing_deceased_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `outgoing_deceased` set       `fullname`=' . (($data['fullname'] !== '' && $data['fullname'] !== NULL) ? "'{$data['fullname']}'" : 'NULL') . ', `gender`=' . (($data['gender'] !== '' && $data['gender'] !== NULL) ? "'{$data['gender']}'" : 'NULL') . ', `tag_number`=' . (($data['tag_number'] !== '' && $data['tag_number'] !== NULL) ? "'{$data['tag_number']}'" : 'NULL') . ', `serial_number`=' . (($data['serial_number'] !== '' && $data['serial_number'] !== NULL) ? "'{$data['serial_number']}'" : 'NULL') . ', `relative_name`=' . (($data['relative_name'] !== '' && $data['relative_name'] !== NULL) ? "'{$data['relative_name']}'" : 'NULL') . ', `relative_phone_number`=' . (($data['relative_phone_number'] !== '' && $data['relative_phone_number'] !== NULL) ? "'{$data['relative_phone_number']}'" : 'NULL') . ', `date`=' . "'{$data['date']}'" . ', `car_out_number`=' . (($data['car_out_number'] !== '' && $data['car_out_number'] !== NULL) ? "'{$data['car_out_number']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"outgoing_deceased_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: outgoing_deceased_after_insert
	if(function_exists('outgoing_deceased_after_insert')){
		$res = sql("select * from `outgoing_deceased` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!outgoing_deceased_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('outgoing_deceased', $recID, getLoggedMemberID());

	return $recID;
}

function outgoing_deceased_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('outgoing_deceased');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='outgoing_deceased' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='outgoing_deceased' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: outgoing_deceased_before_delete
	if(function_exists('outgoing_deceased_before_delete')){
		$args=array();
		if(!outgoing_deceased_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `outgoing_deceased` where `id`='$selected_id'", $eo);

	// hook: outgoing_deceased_after_delete
	if(function_exists('outgoing_deceased_after_delete')){
		$args=array();
		outgoing_deceased_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='outgoing_deceased' and pkValue='$selected_id'", $eo);
}

function outgoing_deceased_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('outgoing_deceased');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='outgoing_deceased' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='outgoing_deceased' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['fullname'] = makeSafe($_REQUEST['fullname']);
		if($data['fullname'] == empty_lookup_value){ $data['fullname'] = ''; }
	if($data['fullname']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fullname': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['gender'] = makeSafe($_REQUEST['fullname']);
		if($data['gender'] == empty_lookup_value){ $data['gender'] = ''; }
	$data['tag_number'] = makeSafe($_REQUEST['fullname']);
		if($data['tag_number'] == empty_lookup_value){ $data['tag_number'] = ''; }
	$data['serial_number'] = makeSafe($_REQUEST['fullname']);
		if($data['serial_number'] == empty_lookup_value){ $data['serial_number'] = ''; }
	$data['relative_name'] = makeSafe($_REQUEST['fullname']);
		if($data['relative_name'] == empty_lookup_value){ $data['relative_name'] = ''; }
	$data['relative_phone_number'] = makeSafe($_REQUEST['fullname']);
		if($data['relative_phone_number'] == empty_lookup_value){ $data['relative_phone_number'] = ''; }
	$data['date'] = parseMySQLDate('', '<%%creationDate%%>');
	$data['car_out_number'] = makeSafe($_REQUEST['car_out_number']);
		if($data['car_out_number'] == empty_lookup_value){ $data['car_out_number'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: outgoing_deceased_before_update
	if(function_exists('outgoing_deceased_before_update')){
		$args=array();
		if(!outgoing_deceased_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `outgoing_deceased` set       `fullname`=' . (($data['fullname'] !== '' && $data['fullname'] !== NULL) ? "'{$data['fullname']}'" : 'NULL') . ', `gender`=' . (($data['gender'] !== '' && $data['gender'] !== NULL) ? "'{$data['gender']}'" : 'NULL') . ', `tag_number`=' . (($data['tag_number'] !== '' && $data['tag_number'] !== NULL) ? "'{$data['tag_number']}'" : 'NULL') . ', `serial_number`=' . (($data['serial_number'] !== '' && $data['serial_number'] !== NULL) ? "'{$data['serial_number']}'" : 'NULL') . ', `relative_name`=' . (($data['relative_name'] !== '' && $data['relative_name'] !== NULL) ? "'{$data['relative_name']}'" : 'NULL') . ', `relative_phone_number`=' . (($data['relative_phone_number'] !== '' && $data['relative_phone_number'] !== NULL) ? "'{$data['relative_phone_number']}'" : 'NULL') . ', `date`=`date`' . ', `car_out_number`=' . (($data['car_out_number'] !== '' && $data['car_out_number'] !== NULL) ? "'{$data['car_out_number']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="outgoing_deceased_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: outgoing_deceased_after_update
	if(function_exists('outgoing_deceased_after_update')){
		$res = sql("SELECT * FROM `outgoing_deceased` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!outgoing_deceased_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='outgoing_deceased' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function outgoing_deceased_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('outgoing_deceased');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_fullname = thisOr(undo_magic_quotes($_REQUEST['filterer_fullname']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: fullname
	$combo_fullname = new DataCombo;
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "mdy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('<%%creationDate%%>', '<%%creationDate%%>');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='outgoing_deceased' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='outgoing_deceased' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `outgoing_deceased` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'outgoing_deceased_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_fullname->SelectedData = $row['fullname'];
		$combo_date->DefaultDate = $row['date'];
	}else{
		$combo_fullname->SelectedData = $filterer_fullname;
	}
	$combo_fullname->HTML = '<span id="fullname-container' . $rnd1 . '"></span><input type="hidden" name="fullname" id="fullname' . $rnd1 . '" value="' . html_attr($combo_fullname->SelectedData) . '">';
	$combo_fullname->MatchText = '<span id="fullname-container-readonly' . $rnd1 . '"></span><input type="hidden" name="fullname" id="fullname' . $rnd1 . '" value="' . html_attr($combo_fullname->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_fullname__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['fullname'] : $filterer_fullname); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(fullname_reload__RAND__) == 'function') fullname_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function fullname_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#fullname-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_fullname__RAND__.value, t: 'outgoing_deceased', f: 'fullname' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="fullname"]').val(resp.results[0].id);
							$j('[id=fullname-container-readonly__RAND__]').html('<span id="fullname-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=incoming_deceased_view_parent]').hide(); }else{ $j('.btn[id=incoming_deceased_view_parent]').show(); }


							if(typeof(fullname_update_autofills__RAND__) == 'function') fullname_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'outgoing_deceased', f: 'fullname' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_fullname__RAND__.value = e.added.id;
				AppGini.current_fullname__RAND__.text = e.added.text;
				$j('[name="fullname"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=incoming_deceased_view_parent]').hide(); }else{ $j('.btn[id=incoming_deceased_view_parent]').show(); }


				if(typeof(fullname_update_autofills__RAND__) == 'function') fullname_update_autofills__RAND__();
			});

			if(!$j("#fullname-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_fullname__RAND__.value, t: 'outgoing_deceased', f: 'fullname' },
					success: function(resp){
						$j('[name="fullname"]').val(resp.results[0].id);
						$j('[id=fullname-container-readonly__RAND__]').html('<span id="fullname-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=incoming_deceased_view_parent]').hide(); }else{ $j('.btn[id=incoming_deceased_view_parent]').show(); }

						if(typeof(fullname_update_autofills__RAND__) == 'function') fullname_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_fullname__RAND__.value, t: 'outgoing_deceased', f: 'fullname' },
				success: function(resp){
					$j('[id=fullname-container__RAND__], [id=fullname-container-readonly__RAND__]').html('<span id="fullname-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=incoming_deceased_view_parent]').hide(); }else{ $j('.btn[id=incoming_deceased_view_parent]').show(); }

					if(typeof(fullname_update_autofills__RAND__) == 'function') fullname_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/outgoing_deceased_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/outgoing_deceased_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Outgoing deceased details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return outgoing_deceased_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return outgoing_deceased_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return outgoing_deceased_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#fullname').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#fullname_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#car_out_number').replaceWith('<div class=\"form-control-static\" id=\"car_out_number\">' + (jQuery('#car_out_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(fullname)%%>', $combo_fullname->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fullname)%%>', $combo_fullname->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(fullname)%%>', urlencode($combo_fullname->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : $combo_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'fullname' => array('incoming_deceased', 'Fullname'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fullname)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(car_out_number)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(fullname)%%>', safe_html($urow['fullname']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(fullname)%%>', html_attr($row['fullname']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fullname)%%>', urlencode($urow['fullname']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', @date('m/d/Y', @strtotime(html_attr($row['date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(@date('m/d/Y', @strtotime(html_attr($urow['date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(car_out_number)%%>', safe_html($urow['car_out_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(car_out_number)%%>', html_attr($row['car_out_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(car_out_number)%%>', urlencode($urow['car_out_number']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fullname)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fullname)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '<%%creationDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('<%%creationDate%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(car_out_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(car_out_number)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';

	$templateCode .= "\tfullname_update_autofills$rnd1 = function(){\n";
	$templateCode .= "\t\t\$j.ajax({\n";
	if($dvprint){
		$templateCode .= "\t\t\turl: 'outgoing_deceased_autofill.php?rnd1=$rnd1&mfk=fullname&id=' + encodeURIComponent('".addslashes($row['fullname'])."'),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "', type: 'GET'\n";
	}else{
		$templateCode .= "\t\t\turl: 'outgoing_deceased_autofill.php?rnd1=$rnd1&mfk=fullname&id=' + encodeURIComponent(AppGini.current_fullname{$rnd1}.value),\n";
		$templateCode .= "\t\t\tcontentType: 'application/x-www-form-urlencoded; charset=" . datalist_db_encoding . "', type: 'GET', beforeSend: function(){ /* */ \$j('#fullname$rnd1').prop('disabled', true); \$j('#fullnameLoading').html('<img src=loading.gif align=top>'); }, complete: function(){".(($arrPerm[1] || (($arrPerm[3] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm[3] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm[3] == 3)) ? "\$j('#fullname$rnd1').prop('disabled', false); " : "\$j('#fullname$rnd1').prop('disabled', true); ")."\$j('#fullnameLoading').html('');}\n";
	}
	$templateCode.="\t\t});\n";
	$templateCode.="\t};\n";
	if(!$dvprint) $templateCode.="\tif(\$j('#fullname_caption').length) \$j('#fullname_caption').click(function(){ /* */ fullname_update_autofills$rnd1(); });\n";


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('outgoing_deceased');
	if($selected_id){
		$jdata = get_joined_record('outgoing_deceased', $selected_id);
		if($jdata === false) $jdata = get_defaults('outgoing_deceased');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('html_attr_tags_ok', $rdata)),
		'jdata' => array_map('nl2br', array_map('html_attr_tags_ok', $jdata))
	);
	$templateCode .= loadView('outgoing_deceased-ajax-cache', $cache_data);

	// hook: outgoing_deceased_dv
	if(function_exists('outgoing_deceased_dv')){
		$args=array();
		outgoing_deceased_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>