<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	/* Configuration */
	/*************************************/

		$pcConfig = array(
			'incoming_deceased' => array(   
				'relative_name' => array(   
					'parent-table' => 'relatives_info',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Incoming deceased',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/application_side_expand.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Fullname', 2 => 'Gender', 3 => 'Tag number', 4 => 'Serial number', 5 => 'Relative name', 6 => 'Relative phone number', 7 => 'Room', 8 => 'Bed', 9 => 'Date'),
					'display-field-names' => array(1 => 'fullname', 2 => 'gender', 3 => 'tag_number', 4 => 'serial_number', 5 => 'relative_name', 6 => 'relative_number', 7 => 'room', 8 => 'bed', 9 => 'date'),
					'sortable-fields' => array(0 => '`incoming_deceased`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => '`relatives_info1`.`first_relative_full_name`', 6 => '`relatives_info1`.`phone_number`', 7 => '`rooms1`.`name`', 8 => 9, 9 => '`incoming_deceased`.`date`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-incoming_deceased',
					'template-printable' => 'children-incoming_deceased-printable',
					'query' => "SELECT `incoming_deceased`.`id` as 'id', `incoming_deceased`.`fullname` as 'fullname', `incoming_deceased`.`gender` as 'gender', `incoming_deceased`.`tag_number` as 'tag_number', `incoming_deceased`.`serial_number` as 'serial_number', IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') as 'relative_name', IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') as 'relative_number', IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') as 'room', IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms2`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms2`.`name`), '') as 'bed', if(`incoming_deceased`.`date`,date_format(`incoming_deceased`.`date`,'%m/%d/%Y'),'') as 'date' FROM `incoming_deceased` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased`.`relative_name` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`incoming_deceased`.`room` LEFT JOIN `beds` as beds1 ON `beds1`.`id`=`incoming_deceased`.`bed` LEFT JOIN `rooms` as rooms2 ON `rooms2`.`id`=`beds1`.`room` "
				),
				'room' => array(   
					'parent-table' => 'rooms',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Incoming deceased',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/application_side_expand.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Fullname', 2 => 'Gender', 3 => 'Tag number', 4 => 'Serial number', 5 => 'Relative name', 6 => 'Relative phone number', 7 => 'Room', 8 => 'Bed', 9 => 'Date'),
					'display-field-names' => array(1 => 'fullname', 2 => 'gender', 3 => 'tag_number', 4 => 'serial_number', 5 => 'relative_name', 6 => 'relative_number', 7 => 'room', 8 => 'bed', 9 => 'date'),
					'sortable-fields' => array(0 => '`incoming_deceased`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => '`relatives_info1`.`first_relative_full_name`', 6 => '`relatives_info1`.`phone_number`', 7 => '`rooms1`.`name`', 8 => 9, 9 => '`incoming_deceased`.`date`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-incoming_deceased',
					'template-printable' => 'children-incoming_deceased-printable',
					'query' => "SELECT `incoming_deceased`.`id` as 'id', `incoming_deceased`.`fullname` as 'fullname', `incoming_deceased`.`gender` as 'gender', `incoming_deceased`.`tag_number` as 'tag_number', `incoming_deceased`.`serial_number` as 'serial_number', IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') as 'relative_name', IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') as 'relative_number', IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') as 'room', IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms2`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms2`.`name`), '') as 'bed', if(`incoming_deceased`.`date`,date_format(`incoming_deceased`.`date`,'%m/%d/%Y'),'') as 'date' FROM `incoming_deceased` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased`.`relative_name` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`incoming_deceased`.`room` LEFT JOIN `beds` as beds1 ON `beds1`.`id`=`incoming_deceased`.`bed` LEFT JOIN `rooms` as rooms2 ON `rooms2`.`id`=`beds1`.`room` "
				),
				'bed' => array(   
					'parent-table' => 'beds',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Incoming deceased',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/application_side_expand.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Fullname', 2 => 'Gender', 3 => 'Tag number', 4 => 'Serial number', 5 => 'Relative name', 6 => 'Relative phone number', 7 => 'Room', 8 => 'Bed', 9 => 'Date'),
					'display-field-names' => array(1 => 'fullname', 2 => 'gender', 3 => 'tag_number', 4 => 'serial_number', 5 => 'relative_name', 6 => 'relative_number', 7 => 'room', 8 => 'bed', 9 => 'date'),
					'sortable-fields' => array(0 => '`incoming_deceased`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => '`relatives_info1`.`first_relative_full_name`', 6 => '`relatives_info1`.`phone_number`', 7 => '`rooms1`.`name`', 8 => 9, 9 => '`incoming_deceased`.`date`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-incoming_deceased',
					'template-printable' => 'children-incoming_deceased-printable',
					'query' => "SELECT `incoming_deceased`.`id` as 'id', `incoming_deceased`.`fullname` as 'fullname', `incoming_deceased`.`gender` as 'gender', `incoming_deceased`.`tag_number` as 'tag_number', `incoming_deceased`.`serial_number` as 'serial_number', IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') as 'relative_name', IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') as 'relative_number', IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') as 'room', IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms2`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms2`.`name`), '') as 'bed', if(`incoming_deceased`.`date`,date_format(`incoming_deceased`.`date`,'%m/%d/%Y'),'') as 'date' FROM `incoming_deceased` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased`.`relative_name` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`incoming_deceased`.`room` LEFT JOIN `beds` as beds1 ON `beds1`.`id`=`incoming_deceased`.`bed` LEFT JOIN `rooms` as rooms2 ON `rooms2`.`id`=`beds1`.`room` "
				)
			),
			'outgoing_deceased' => array(   
				'fullname' => array(   
					'parent-table' => 'incoming_deceased',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Outgoing deceased',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/application_side_contract.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Fullname', 2 => 'Gender', 3 => 'Tag number', 4 => 'Serial number', 5 => 'Relative name', 6 => 'Relative phone number', 7 => 'Date', 8 => 'Car out number'),
					'display-field-names' => array(1 => 'fullname', 2 => 'gender', 3 => 'tag_number', 4 => 'serial_number', 5 => 'relative_name', 6 => 'relative_phone_number', 7 => 'date', 8 => 'car_out_number'),
					'sortable-fields' => array(0 => '`outgoing_deceased`.`id`', 1 => '`incoming_deceased1`.`fullname`', 2 => '`incoming_deceased1`.`gender`', 3 => '`incoming_deceased1`.`tag_number`', 4 => '`incoming_deceased1`.`serial_number`', 5 => 6, 6 => 7, 7 => '`outgoing_deceased`.`date`', 8 => 9),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-outgoing_deceased',
					'template-printable' => 'children-outgoing_deceased-printable',
					'query' => "SELECT `outgoing_deceased`.`id` as 'id', IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`), CONCAT_WS('',   `incoming_deceased1`.`fullname`), '') as 'fullname', IF(    CHAR_LENGTH(`incoming_deceased1`.`gender`), CONCAT_WS('',   `incoming_deceased1`.`gender`), '') as 'gender', IF(    CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`tag_number`), '') as 'tag_number', IF(    CHAR_LENGTH(`incoming_deceased1`.`serial_number`), CONCAT_WS('',   `incoming_deceased1`.`serial_number`), '') as 'serial_number', IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`), '') as 'relative_name', IF(    CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`phone_number`), '') as 'relative_phone_number', if(`outgoing_deceased`.`date`,date_format(`outgoing_deceased`.`date`,'%m/%d/%Y'),'') as 'date', `outgoing_deceased`.`car_out_number` as 'car_out_number' FROM `outgoing_deceased` LEFT JOIN `incoming_deceased` as incoming_deceased1 ON `incoming_deceased1`.`id`=`outgoing_deceased`.`fullname` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased1`.`relative_name` "
				)
			),
			'relatives_info' => array(   
			),
			'rooms' => array(   
			),
			'beds' => array(   
				'room' => array(   
					'parent-table' => 'rooms',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Beds',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/tag_green.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Number', 2 => 'Room', 3 => 'Status'),
					'display-field-names' => array(1 => 'number', 2 => 'room', 3 => 'status'),
					'sortable-fields' => array(0 => '`beds`.`id`', 1 => 2, 2 => '`rooms1`.`name`', 3 => 4),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-beds',
					'template-printable' => 'children-beds-printable',
					'query' => "SELECT `beds`.`id` as 'id', `beds`.`number` as 'number', IF(    CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `rooms1`.`name`), '') as 'room', `beds`.`status` as 'status' FROM `beds` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`beds`.`room` "
				)
			),
			'bill' => array(   
				'deceased' => array(   
					'parent-table' => 'invoices',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Bill',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/account_balances.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Deceased', 2 => 'Total', 3 => 'Paid amount', 4 => 'Balance'),
					'display-field-names' => array(1 => 'deceased', 2 => 'total', 3 => 'paid_amount', 4 => 'balance'),
					'sortable-fields' => array(0 => '`bill`.`id`', 1 => 2, 2 => '`invoices1`.`total`', 3 => '`bill`.`paid_amount`', 4 => '`invoices1`.`balance`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-bill',
					'template-printable' => 'children-bill-printable',
					'query' => "SELECT `bill`.`id` as 'id', IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') as 'deceased', IF(    CHAR_LENGTH(`invoices1`.`total`), CONCAT_WS('',   `invoices1`.`total`), '') as 'total', `bill`.`paid_amount` as 'paid_amount', IF(    CHAR_LENGTH(`invoices1`.`balance`), CONCAT_WS('',   `invoices1`.`balance`), '') as 'balance' FROM `bill` LEFT JOIN `invoices` as invoices1 ON `invoices1`.`id`=`bill`.`deceased` LEFT JOIN `incoming_deceased` as incoming_deceased1 ON `incoming_deceased1`.`id`=`invoices1`.`deceased` "
				)
			),
			'invoices' => array(   
				'deceased' => array(   
					'parent-table' => 'incoming_deceased',
					'parent-primary-key' => 'id',
					'child-primary-key' => 'id',
					'child-primary-key-index' => 0,
					'tab-label' => 'Invoices',
					'auto-close' => true,
					'table-icon' => 'resources/table_icons/card_money.png',
					'display-refresh' => true,
					'display-add-new' => true,
					'forced-where' => '',
					'display-fields' => array(1 => 'Deceased', 2 => 'Bed/Room', 3 => 'Relative', 4 => 'Services', 5 => 'Total', 6 => 'Balance', 7 => 'Date'),
					'display-field-names' => array(1 => 'deceased', 2 => 'room', 3 => 'relative', 4 => 'services', 5 => 'total', 6 => 'balance', 7 => 'date'),
					'sortable-fields' => array(0 => '`invoices`.`id`', 1 => 2, 2 => 3, 3 => 4, 4 => 5, 5 => '`invoices`.`total`', 6 => '`invoices`.`balance`', 7 => '`invoices`.`date`'),
					'records-per-page' => 10,
					'default-sort-by' => false,
					'default-sort-direction' => 'asc',
					'open-detail-view-on-click' => true,
					'display-page-selector' => true,
					'show-page-progress' => true,
					'template' => 'children-invoices',
					'template-printable' => 'children-invoices-printable',
					'query' => "SELECT `invoices`.`id` as 'id', IF(    CHAR_LENGTH(`incoming_deceased1`.`fullname`) || CHAR_LENGTH(`incoming_deceased1`.`tag_number`), CONCAT_WS('',   `incoming_deceased1`.`fullname`, '  TagNo:', `incoming_deceased1`.`tag_number`), '') as 'deceased', IF(    CHAR_LENGTH(`beds1`.`number`) || CHAR_LENGTH(`rooms1`.`name`), CONCAT_WS('',   `beds1`.`number`, ' Room: ', `rooms1`.`name`), '') as 'room', IF(    CHAR_LENGTH(`relatives_info1`.`first_relative_full_name`) || CHAR_LENGTH(`relatives_info1`.`phone_number`), CONCAT_WS('',   `relatives_info1`.`first_relative_full_name`, '  Phone: ', `relatives_info1`.`phone_number`), '') as 'relative', `invoices`.`services` as 'services', `invoices`.`total` as 'total', `invoices`.`balance` as 'balance', if(`invoices`.`date`,date_format(`invoices`.`date`,'%m/%d/%Y'),'') as 'date' FROM `invoices` LEFT JOIN `incoming_deceased` as incoming_deceased1 ON `incoming_deceased1`.`id`=`invoices`.`deceased` LEFT JOIN `beds` as beds1 ON `beds1`.`id`=`incoming_deceased1`.`bed` LEFT JOIN `rooms` as rooms1 ON `rooms1`.`id`=`beds1`.`room` LEFT JOIN `relatives_info` as relatives_info1 ON `relatives_info1`.`id`=`incoming_deceased1`.`relative_name` "
				)
			)
		);

	/*************************************/
	/* End of configuration */


	$currDir = dirname(__FILE__);
	include("{$currDir}/defaultLang.php");
	include("{$currDir}/language.php");
	include("{$currDir}/lib.php");
	@header('Content-Type: text/html; charset=' . datalist_db_encoding);

	handle_maintenance();

	/**
	* dynamic configuration based on current user's permissions
	* $userPCConfig array is populated only with parent tables where the user has access to
	* at least one child table
	*/
	$userPCConfig = array();
	foreach($pcConfig as $pcChildTable => $ChildrenLookups){
		$permChild = getTablePermissions($pcChildTable);
		if($permChild[2]){ // user can view records of the child table, so proceed to check children lookups
			foreach($ChildrenLookups as $ChildLookupField => $ChildConfig){
				$permParent = getTablePermissions($ChildConfig['parent-table']);
				if($permParent[2]){ // user can view records of parent table
					$userPCConfig[$pcChildTable][$ChildLookupField] = $pcConfig[$pcChildTable][$ChildLookupField];
					// show add new only if configured above AND the user has insert permission
					if($permChild[1] && $pcConfig[$pcChildTable][$ChildLookupField]['display-add-new']){
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = true;
					}else{
						$userPCConfig[$pcChildTable][$ChildLookupField]['display-add-new'] = false;
					}
				}
			}
		}
	}

	/* Receive, UTF-convert, and validate parameters */
	$ParentTable = $_REQUEST['ParentTable']; // needed only with operation=show-children, will be validated in the processing code
	$ChildTable = $_REQUEST['ChildTable'];
		if(!in_array($ChildTable, array_keys($userPCConfig))){
			/* defaults to first child table in config array if not provided */
			$ChildTable = current(array_keys($userPCConfig));
		}
		if(!$ChildTable){ die('<!-- No tables accessible to current user -->'); }
	$SelectedID = strip_tags($_REQUEST['SelectedID']);
	$ChildLookupField = $_REQUEST['ChildLookupField'];
		if(!in_array($ChildLookupField, array_keys($userPCConfig[$ChildTable]))){
			/* defaults to first lookup in current child config array if not provided */
			$ChildLookupField = current(array_keys($userPCConfig[$ChildTable]));
		}
	$Page = intval($_REQUEST['Page']);
		if($Page < 1){
			$Page = 1;
		}
	$SortBy = ($_REQUEST['SortBy'] != '' ? abs(intval($_REQUEST['SortBy'])) : false);
		if(!in_array($SortBy, array_keys($userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields']), true)){
			$SortBy = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-by'];
		}
	$SortDirection = strtolower($_REQUEST['SortDirection']);
		if(!in_array($SortDirection, array('asc', 'desc'))){
			$SortDirection = $userPCConfig[$ChildTable][$ChildLookupField]['default-sort-direction'];
		}
	$Operation = strtolower($_REQUEST['Operation']);
		if(!in_array($Operation, array('get-records', 'show-children', 'get-records-printable', 'show-children-printable'))){
			$Operation = 'get-records';
		}

	/* process requested operation */
	switch($Operation){
		/************************************************/
		case 'show-children':
			/* populate HTML and JS content with children tabs */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<li%s><a href="#panel_%s-%s" id="tab_%s-%s" data-toggle="tab">%s%s</a></li>' . "\n\t\t\t\t\t",($tabLabels ? '' : ' class="active"'), $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="tab-pane%s"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, ($tabPanels ? '' : ' active'), $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs">
				<ul class="nav nav-tabs">
					<?php echo $tabLabels; ?>
				</ul>
				<span id="pc-loading"></span>
			</div>
			<div class="tab-content"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'show-children-printable':
			/* populate HTML and JS content with children buttons */
			$tabLabels = $tabPanels = $tabLoaders = '';
			foreach($userPCConfig as $ChildTable => $childLookups){
				foreach($childLookups as $ChildLookupField => $childConfig){
					if($childConfig['parent-table'] == $ParentTable){
						$TableIcon = ($childConfig['table-icon'] ? "<img src=\"{$childConfig['table-icon']}\" border=\"0\" />" : '');
						$tabLabels .= sprintf('<button type="button" class="btn btn-default" data-target="#panel_%s-%s" id="tab_%s-%s" data-toggle="collapse">%s %s</button>' . "\n\t\t\t\t\t", $ChildTable, $ChildLookupField, $ChildTable, $ChildLookupField, $TableIcon, $childConfig['tab-label']);
						$tabPanels .= sprintf('<div id="panel_%s-%s" class="collapse"><img src="loading.gif" align="top" />%s</div>' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, $Translation['Loading ...']);
						$tabLoaders .= sprintf('post("parent-children.php", { ChildTable: "%s", ChildLookupField: "%s", SelectedID: "%s", Page: 1, SortBy: "", SortDirection: "", Operation: "get-records-printable" }, "panel_%s-%s");' . "\n\t\t\t\t", $ChildTable, $ChildLookupField, addslashes($SelectedID), $ChildTable, $ChildLookupField);
					}
				}
			}

			if(!$tabLabels){ die('<!-- no children of current parent table are accessible to current user -->'); }
			?>
			<div id="children-tabs" class="hidden-print">
				<div class="btn-group btn-group-lg">
					<?php echo $tabLabels; ?>
				</div>
				<span id="pc-loading"></span>
			</div>
			<div class="vspacer-lg"><?php echo $tabPanels; ?></div>

			<script>
				$j(function(){
					/* for iOS, avoid loading child tabs in modals */
					var iOS = /(iPad|iPhone|iPod)/g.test(navigator.userAgent);
					var embedded = ($j('.navbar').length == 0);
					if(iOS && embedded){
						$j('#children-tabs').next('.tab-content').remove();
						$j('#children-tabs').remove();
						return;
					}

					/* ajax loading of each tab's contents */
					<?php echo $tabLoaders; ?>
				})
			</script>
			<?php
			break;

		/************************************************/
		case 'get-records-printable':
		default: /* default is 'get-records' */

			if($Operation == 'get-records-printable'){
				$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] = 2000;
			}

			// build the user permissions limiter
			$permissionsWhere = $permissionsJoin = '';
			$permChild = getTablePermissions($ChildTable);
			if($permChild[2] == 1){ // user can view only his own records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND LCASE(`membership_userrecords`.`memberID`)='".getLoggedMemberID()."'";
			}elseif($permChild[2] == 2){ // user can view only his group's records
				$permissionsWhere = "`$ChildTable`.`{$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key']}`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='$ChildTable' AND `membership_userrecords`.`groupID`='".getLoggedGroupID()."'";
			}elseif($permChild[2] == 3){ // user can view all records
				/* that's the only case remaining ... no need to modify the query in this case */
			}
			$permissionsJoin = ($permissionsWhere ? ", `membership_userrecords`" : '');

			// build the count query
			$forcedWhere = $userPCConfig[$ChildTable][$ChildLookupField]['forced-where'];
			$query = 
				preg_replace('/^select .* from /i', 'SELECT count(1) FROM ', $userPCConfig[$ChildTable][$ChildLookupField]['query']) .
				$permissionsJoin . " WHERE " .
				($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
				($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
				"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'";
			$totalMatches = sqlValue($query);

			// make sure $Page is <= max pages
			$maxPage = ceil($totalMatches / $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']);
			if($Page > $maxPage){ $Page = $maxPage; }

			// initiate output data array
			$data = array(
				'config' => $userPCConfig[$ChildTable][$ChildLookupField],
				'parameters' => array(
					'ChildTable' => $ChildTable,
					'ChildLookupField' => $ChildLookupField,
					'SelectedID' => $SelectedID,
					'Page' => $Page,
					'SortBy' => $SortBy,
					'SortDirection' => $SortDirection,
					'Operation' => $Operation
				),
				'records' => array(),
				'totalMatches' => $totalMatches
			);

			// build the data query
			if($totalMatches){ // if we have at least one record, proceed with fetching data
				$startRecord = $userPCConfig[$ChildTable][$ChildLookupField]['records-per-page'] * ($Page - 1);
				$data['query'] = 
					$userPCConfig[$ChildTable][$ChildLookupField]['query'] .
					$permissionsJoin . " WHERE " .
					($permissionsWhere ? "( $permissionsWhere )" : "( 1=1 )") . " AND " .
					($forcedWhere ? "( $forcedWhere )" : "( 2=2 )") . " AND " .
					"`$ChildTable`.`$ChildLookupField`='" . makeSafe($SelectedID) . "'" . 
					($SortBy !== false && $userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy] ? " ORDER BY {$userPCConfig[$ChildTable][$ChildLookupField]['sortable-fields'][$SortBy]} $SortDirection" : '') .
					" LIMIT $startRecord, {$userPCConfig[$ChildTable][$ChildLookupField]['records-per-page']}";
				$res = sql($data['query'], $eo);
				while($row = db_fetch_row($res)){
					$data['records'][$row[$userPCConfig[$ChildTable][$ChildLookupField]['child-primary-key-index']]] = $row;
				}
			}else{ // if no matching records
				$startRecord = 0;
			}

			if($Operation == 'get-records-printable'){
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template-printable'], $data);
			}else{
				$response = loadView($userPCConfig[$ChildTable][$ChildLookupField]['template'], $data);
			}

			// change name space to ensure uniqueness
			$uniqueNameSpace = $ChildTable.ucfirst($ChildLookupField).'GetRecords';
			echo str_replace("{$ChildTable}GetChildrenRecordsList", $uniqueNameSpace, $response);
		/************************************************/
	}
