<?php
// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/relatives_info.php");
	include("$currDir/relatives_info_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('relatives_info');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "relatives_info";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`relatives_info`.`id`" => "id",
		"`relatives_info`.`first_relative_full_name`" => "first_relative_full_name",
		"`relatives_info`.`home_address`" => "home_address",
		"`relatives_info`.`home_town`" => "home_town",
		"`relatives_info`.`occupation`" => "occupation",
		"`relatives_info`.`phone_number`" => "phone_number",
		"`relatives_info`.`second_relative_full_name`" => "second_relative_full_name",
		"`relatives_info`.`second_relative_home_address`" => "second_relative_home_address",
		"`relatives_info`.`second_relative_home_town`" => "second_relative_home_town",
		"`relatives_info`.`second_relative_occupation`" => "second_relative_occupation",
		"`relatives_info`.`second_relative_phone_number`" => "second_relative_phone_number"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`relatives_info`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`relatives_info`.`id`" => "id",
		"`relatives_info`.`first_relative_full_name`" => "first_relative_full_name",
		"`relatives_info`.`home_address`" => "home_address",
		"`relatives_info`.`home_town`" => "home_town",
		"`relatives_info`.`occupation`" => "occupation",
		"`relatives_info`.`phone_number`" => "phone_number",
		"`relatives_info`.`second_relative_full_name`" => "second_relative_full_name",
		"`relatives_info`.`second_relative_home_address`" => "second_relative_home_address",
		"`relatives_info`.`second_relative_home_town`" => "second_relative_home_town",
		"`relatives_info`.`second_relative_occupation`" => "second_relative_occupation",
		"`relatives_info`.`second_relative_phone_number`" => "second_relative_phone_number"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`relatives_info`.`id`" => "ID",
		"`relatives_info`.`first_relative_full_name`" => "First relative full name",
		"`relatives_info`.`home_address`" => "Home address",
		"`relatives_info`.`home_town`" => "Home town",
		"`relatives_info`.`occupation`" => "Occupation",
		"`relatives_info`.`phone_number`" => "Phone number",
		"`relatives_info`.`second_relative_full_name`" => "Second relative full name",
		"`relatives_info`.`second_relative_home_address`" => "Second relative home address",
		"`relatives_info`.`second_relative_home_town`" => "Second relative home town",
		"`relatives_info`.`second_relative_occupation`" => "Second relative occupation",
		"`relatives_info`.`second_relative_phone_number`" => "Second relative phone number"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`relatives_info`.`id`" => "id",
		"`relatives_info`.`first_relative_full_name`" => "first_relative_full_name",
		"`relatives_info`.`home_address`" => "home_address",
		"`relatives_info`.`home_town`" => "home_town",
		"`relatives_info`.`occupation`" => "occupation",
		"`relatives_info`.`phone_number`" => "phone_number",
		"`relatives_info`.`second_relative_full_name`" => "second_relative_full_name",
		"`relatives_info`.`second_relative_home_address`" => "second_relative_home_address",
		"`relatives_info`.`second_relative_home_town`" => "second_relative_home_town",
		"`relatives_info`.`second_relative_occupation`" => "second_relative_occupation",
		"`relatives_info`.`second_relative_phone_number`" => "second_relative_phone_number"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`relatives_info` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "relatives_info_view.php";
	$x->RedirectAfterInsert = "relatives_info_view.php?SelectedID=#ID#";
	$x->TableTitle = "Relatives info";
	$x->TableIcon = "resources/table_icons/group.png";
	$x->PrimaryKey = "`relatives_info`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("First relative full name", "Home address", "Home town", "Occupation", "Phone number", "Second relative full name", "Second relative home address", "Second relative home town", "Second relative occupation", "Second relative phone number");
	$x->ColFieldName = array('first_relative_full_name', 'home_address', 'home_town', 'occupation', 'phone_number', 'second_relative_full_name', 'second_relative_home_address', 'second_relative_home_town', 'second_relative_occupation', 'second_relative_phone_number');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/relatives_info_templateTV.html';
	$x->SelectedTemplate = 'templates/relatives_info_templateTVS.html';
	$x->TemplateDV = 'templates/relatives_info_templateDV.html';
	$x->TemplateDVP = 'templates/relatives_info_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `relatives_info`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='relatives_info' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `relatives_info`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='relatives_info' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`relatives_info`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: relatives_info_init
	$render=TRUE;
	if(function_exists('relatives_info_init')){
		$args=array();
		$render=relatives_info_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: relatives_info_header
	$headerCode='';
	if(function_exists('relatives_info_header')){
		$args=array();
		$headerCode=relatives_info_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: relatives_info_footer
	$footerCode='';
	if(function_exists('relatives_info_footer')){
		$args=array();
		$footerCode=relatives_info_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>