<?php

// Data functions (insert, update, delete, form) for table relatives_info

// This script and data application were generated by AppGini 5.71
// Download AppGini for free from https://bigprof.com/appgini/download/

function relatives_info_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('relatives_info');
	if(!$arrPerm[1]){
		return false;
	}

	$data['first_relative_full_name'] = makeSafe($_REQUEST['first_relative_full_name']);
		if($data['first_relative_full_name'] == empty_lookup_value){ $data['first_relative_full_name'] = ''; }
	$data['home_address'] = makeSafe($_REQUEST['home_address']);
		if($data['home_address'] == empty_lookup_value){ $data['home_address'] = ''; }
	$data['home_town'] = makeSafe($_REQUEST['home_town']);
		if($data['home_town'] == empty_lookup_value){ $data['home_town'] = ''; }
	$data['occupation'] = makeSafe($_REQUEST['occupation']);
		if($data['occupation'] == empty_lookup_value){ $data['occupation'] = ''; }
	$data['phone_number'] = makeSafe($_REQUEST['phone_number']);
		if($data['phone_number'] == empty_lookup_value){ $data['phone_number'] = ''; }
	$data['second_relative_full_name'] = makeSafe($_REQUEST['second_relative_full_name']);
		if($data['second_relative_full_name'] == empty_lookup_value){ $data['second_relative_full_name'] = ''; }
	$data['second_relative_home_address'] = makeSafe($_REQUEST['second_relative_home_address']);
		if($data['second_relative_home_address'] == empty_lookup_value){ $data['second_relative_home_address'] = ''; }
	$data['second_relative_home_town'] = makeSafe($_REQUEST['second_relative_home_town']);
		if($data['second_relative_home_town'] == empty_lookup_value){ $data['second_relative_home_town'] = ''; }
	$data['second_relative_occupation'] = makeSafe($_REQUEST['second_relative_occupation']);
		if($data['second_relative_occupation'] == empty_lookup_value){ $data['second_relative_occupation'] = ''; }
	$data['second_relative_phone_number'] = makeSafe($_REQUEST['second_relative_phone_number']);
		if($data['second_relative_phone_number'] == empty_lookup_value){ $data['second_relative_phone_number'] = ''; }
	if($data['first_relative_full_name']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'First relative full name': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['home_address']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Home address': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['home_town']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Home town': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['occupation']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Occupation': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['phone_number']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Phone number': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: relatives_info_before_insert
	if(function_exists('relatives_info_before_insert')){
		$args=array();
		if(!relatives_info_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `relatives_info` set       `first_relative_full_name`=' . (($data['first_relative_full_name'] !== '' && $data['first_relative_full_name'] !== NULL) ? "'{$data['first_relative_full_name']}'" : 'NULL') . ', `home_address`=' . (($data['home_address'] !== '' && $data['home_address'] !== NULL) ? "'{$data['home_address']}'" : 'NULL') . ', `home_town`=' . (($data['home_town'] !== '' && $data['home_town'] !== NULL) ? "'{$data['home_town']}'" : 'NULL') . ', `occupation`=' . (($data['occupation'] !== '' && $data['occupation'] !== NULL) ? "'{$data['occupation']}'" : 'NULL') . ', `phone_number`=' . (($data['phone_number'] !== '' && $data['phone_number'] !== NULL) ? "'{$data['phone_number']}'" : 'NULL') . ', `second_relative_full_name`=' . (($data['second_relative_full_name'] !== '' && $data['second_relative_full_name'] !== NULL) ? "'{$data['second_relative_full_name']}'" : 'NULL') . ', `second_relative_home_address`=' . (($data['second_relative_home_address'] !== '' && $data['second_relative_home_address'] !== NULL) ? "'{$data['second_relative_home_address']}'" : 'NULL') . ', `second_relative_home_town`=' . (($data['second_relative_home_town'] !== '' && $data['second_relative_home_town'] !== NULL) ? "'{$data['second_relative_home_town']}'" : 'NULL') . ', `second_relative_occupation`=' . (($data['second_relative_occupation'] !== '' && $data['second_relative_occupation'] !== NULL) ? "'{$data['second_relative_occupation']}'" : 'NULL') . ', `second_relative_phone_number`=' . (($data['second_relative_phone_number'] !== '' && $data['second_relative_phone_number'] !== NULL) ? "'{$data['second_relative_phone_number']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"relatives_info_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: relatives_info_after_insert
	if(function_exists('relatives_info_after_insert')){
		$res = sql("select * from `relatives_info` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!relatives_info_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('relatives_info', $recID, getLoggedMemberID());

	return $recID;
}

function relatives_info_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('relatives_info');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='relatives_info' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='relatives_info' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: relatives_info_before_delete
	if(function_exists('relatives_info_before_delete')){
		$args=array();
		if(!relatives_info_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: incoming_deceased
	$res = sql("select `id` from `relatives_info` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `incoming_deceased` where `relative_name`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "incoming_deceased", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "incoming_deceased", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='relatives_info_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='relatives_info_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `relatives_info` where `id`='$selected_id'", $eo);

	// hook: relatives_info_after_delete
	if(function_exists('relatives_info_after_delete')){
		$args=array();
		relatives_info_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='relatives_info' and pkValue='$selected_id'", $eo);
}

function relatives_info_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('relatives_info');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='relatives_info' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='relatives_info' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['first_relative_full_name'] = makeSafe($_REQUEST['first_relative_full_name']);
		if($data['first_relative_full_name'] == empty_lookup_value){ $data['first_relative_full_name'] = ''; }
	if($data['first_relative_full_name']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'First relative full name': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['home_address'] = makeSafe($_REQUEST['home_address']);
		if($data['home_address'] == empty_lookup_value){ $data['home_address'] = ''; }
	if($data['home_address']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Home address': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['home_town'] = makeSafe($_REQUEST['home_town']);
		if($data['home_town'] == empty_lookup_value){ $data['home_town'] = ''; }
	if($data['home_town']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Home town': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['occupation'] = makeSafe($_REQUEST['occupation']);
		if($data['occupation'] == empty_lookup_value){ $data['occupation'] = ''; }
	if($data['occupation']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Occupation': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['phone_number'] = makeSafe($_REQUEST['phone_number']);
		if($data['phone_number'] == empty_lookup_value){ $data['phone_number'] = ''; }
	if($data['phone_number']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Phone number': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['second_relative_full_name'] = makeSafe($_REQUEST['second_relative_full_name']);
		if($data['second_relative_full_name'] == empty_lookup_value){ $data['second_relative_full_name'] = ''; }
	$data['second_relative_home_address'] = makeSafe($_REQUEST['second_relative_home_address']);
		if($data['second_relative_home_address'] == empty_lookup_value){ $data['second_relative_home_address'] = ''; }
	$data['second_relative_home_town'] = makeSafe($_REQUEST['second_relative_home_town']);
		if($data['second_relative_home_town'] == empty_lookup_value){ $data['second_relative_home_town'] = ''; }
	$data['second_relative_occupation'] = makeSafe($_REQUEST['second_relative_occupation']);
		if($data['second_relative_occupation'] == empty_lookup_value){ $data['second_relative_occupation'] = ''; }
	$data['second_relative_phone_number'] = makeSafe($_REQUEST['second_relative_phone_number']);
		if($data['second_relative_phone_number'] == empty_lookup_value){ $data['second_relative_phone_number'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: relatives_info_before_update
	if(function_exists('relatives_info_before_update')){
		$args=array();
		if(!relatives_info_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `relatives_info` set       `first_relative_full_name`=' . (($data['first_relative_full_name'] !== '' && $data['first_relative_full_name'] !== NULL) ? "'{$data['first_relative_full_name']}'" : 'NULL') . ', `home_address`=' . (($data['home_address'] !== '' && $data['home_address'] !== NULL) ? "'{$data['home_address']}'" : 'NULL') . ', `home_town`=' . (($data['home_town'] !== '' && $data['home_town'] !== NULL) ? "'{$data['home_town']}'" : 'NULL') . ', `occupation`=' . (($data['occupation'] !== '' && $data['occupation'] !== NULL) ? "'{$data['occupation']}'" : 'NULL') . ', `phone_number`=' . (($data['phone_number'] !== '' && $data['phone_number'] !== NULL) ? "'{$data['phone_number']}'" : 'NULL') . ', `second_relative_full_name`=' . (($data['second_relative_full_name'] !== '' && $data['second_relative_full_name'] !== NULL) ? "'{$data['second_relative_full_name']}'" : 'NULL') . ', `second_relative_home_address`=' . (($data['second_relative_home_address'] !== '' && $data['second_relative_home_address'] !== NULL) ? "'{$data['second_relative_home_address']}'" : 'NULL') . ', `second_relative_home_town`=' . (($data['second_relative_home_town'] !== '' && $data['second_relative_home_town'] !== NULL) ? "'{$data['second_relative_home_town']}'" : 'NULL') . ', `second_relative_occupation`=' . (($data['second_relative_occupation'] !== '' && $data['second_relative_occupation'] !== NULL) ? "'{$data['second_relative_occupation']}'" : 'NULL') . ', `second_relative_phone_number`=' . (($data['second_relative_phone_number'] !== '' && $data['second_relative_phone_number'] !== NULL) ? "'{$data['second_relative_phone_number']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="relatives_info_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: relatives_info_after_update
	if(function_exists('relatives_info_after_update')){
		$res = sql("SELECT * FROM `relatives_info` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!relatives_info_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='relatives_info' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function relatives_info_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('relatives_info');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='relatives_info' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='relatives_info' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `relatives_info` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'relatives_info_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
	}else{
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function(){
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/relatives_info_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/relatives_info_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Relatives info details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return relatives_info_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return relatives_info_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return relatives_info_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#first_relative_full_name').replaceWith('<div class=\"form-control-static\" id=\"first_relative_full_name\">' + (jQuery('#first_relative_full_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#home_address').replaceWith('<div class=\"form-control-static\" id=\"home_address\">' + (jQuery('#home_address').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#home_town').replaceWith('<div class=\"form-control-static\" id=\"home_town\">' + (jQuery('#home_town').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#occupation').replaceWith('<div class=\"form-control-static\" id=\"occupation\">' + (jQuery('#occupation').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#phone_number').replaceWith('<div class=\"form-control-static\" id=\"phone_number\">' + (jQuery('#phone_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#second_relative_full_name').replaceWith('<div class=\"form-control-static\" id=\"second_relative_full_name\">' + (jQuery('#second_relative_full_name').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#second_relative_home_address').replaceWith('<div class=\"form-control-static\" id=\"second_relative_home_address\">' + (jQuery('#second_relative_home_address').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#second_relative_home_town').replaceWith('<div class=\"form-control-static\" id=\"second_relative_home_town\">' + (jQuery('#second_relative_home_town').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#second_relative_occupation').replaceWith('<div class=\"form-control-static\" id=\"second_relative_occupation\">' + (jQuery('#second_relative_occupation').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#second_relative_phone_number').replaceWith('<div class=\"form-control-static\" id=\"second_relative_phone_number\">' + (jQuery('#second_relative_phone_number').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(first_relative_full_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(home_address)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(home_town)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(occupation)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(phone_number)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(second_relative_full_name)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(second_relative_home_address)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(second_relative_home_town)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(second_relative_occupation)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(second_relative_phone_number)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(first_relative_full_name)%%>', safe_html($urow['first_relative_full_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(first_relative_full_name)%%>', html_attr($row['first_relative_full_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(first_relative_full_name)%%>', urlencode($urow['first_relative_full_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(home_address)%%>', safe_html($urow['home_address']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(home_address)%%>', html_attr($row['home_address']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(home_address)%%>', urlencode($urow['home_address']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(home_town)%%>', safe_html($urow['home_town']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(home_town)%%>', html_attr($row['home_town']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(home_town)%%>', urlencode($urow['home_town']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(occupation)%%>', safe_html($urow['occupation']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(occupation)%%>', html_attr($row['occupation']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(occupation)%%>', urlencode($urow['occupation']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(phone_number)%%>', safe_html($urow['phone_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(phone_number)%%>', html_attr($row['phone_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_number)%%>', urlencode($urow['phone_number']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(second_relative_full_name)%%>', safe_html($urow['second_relative_full_name']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(second_relative_full_name)%%>', html_attr($row['second_relative_full_name']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_full_name)%%>', urlencode($urow['second_relative_full_name']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(second_relative_home_address)%%>', safe_html($urow['second_relative_home_address']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(second_relative_home_address)%%>', html_attr($row['second_relative_home_address']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_home_address)%%>', urlencode($urow['second_relative_home_address']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(second_relative_home_town)%%>', safe_html($urow['second_relative_home_town']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(second_relative_home_town)%%>', html_attr($row['second_relative_home_town']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_home_town)%%>', urlencode($urow['second_relative_home_town']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(second_relative_occupation)%%>', safe_html($urow['second_relative_occupation']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(second_relative_occupation)%%>', html_attr($row['second_relative_occupation']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_occupation)%%>', urlencode($urow['second_relative_occupation']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(second_relative_phone_number)%%>', safe_html($urow['second_relative_phone_number']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(second_relative_phone_number)%%>', html_attr($row['second_relative_phone_number']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_phone_number)%%>', urlencode($urow['second_relative_phone_number']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(first_relative_full_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(first_relative_full_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(home_address)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(home_address)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(home_town)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(home_town)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(occupation)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(occupation)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(phone_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(phone_number)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(second_relative_full_name)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_full_name)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(second_relative_home_address)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_home_address)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(second_relative_home_town)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_home_town)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(second_relative_occupation)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_occupation)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(second_relative_phone_number)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(second_relative_phone_number)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('relatives_info');
	if($selected_id){
		$jdata = get_joined_record('relatives_info', $selected_id);
		if($jdata === false) $jdata = get_defaults('relatives_info');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('html_attr_tags_ok', $rdata)),
		'jdata' => array_map('nl2br', array_map('html_attr_tags_ok', $jdata))
	);
	$templateCode .= loadView('relatives_info-ajax-cache', $cache_data);

	// hook: relatives_info_dv
	if(function_exists('relatives_info_dv')){
		$args=array();
		relatives_info_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>